###################################################################
# Dockerfile to build instance of CentOS with additional predefined
# configuration items
###################################################################

FROM centos:7

MAINTAINER Ray Elenteny - Elasticsearch Meetup 07/26/2016

RUN yum -y update && \
    yum -y install hostname zip unzip tar sudo nc
